### ISSUE TITLE
题库答案错误

### ISSUE THREAD

**Issue by phoenixgao** [wansir/tounao#10]
2018/01/14 16:27:05 成语「奇货可居」的典故与哪位历史人物有关？
2018/01/14 16:27:05 嬴政
2018/01/14 16:27:05 白起[标答]
2018/01/14 16:27:05 吕不韦
2018/01/14 16:27:05 商鞅

应为吕不韦

2018/01/14 19:31:17 三国时期名将赵子龙的故乡是？
2018/01/14 19:31:17 湖北省
2018/01/14 19:31:17 湖南省[标答]
2018/01/14 19:31:17 河北省
2018/01/14 19:31:17 河南省

应为河北省

2018/01/14 19:31:27 旧约「创世纪」中，亚当和夏娃的居所，被称为「人间乐园」的是？
2018/01/14 19:31:27 园明园
2018/01/14 19:31:27 青苹果园
2018/01/14 19:31:27 伊甸园
2018/01/14 19:31:27 陈园园[标答]

应为伊甸园

2018/01/14 19:24:16 目前研究发现我国境内最古老的人类是？
2018/01/14 19:24:16 元谋人
2018/01/14 19:24:16 山顶洞人
2018/01/14 19:24:16 北京人[标答]
2018/01/14 19:24:16 丁村人

应为元谋人

2018/01/14 19:35:43 世界上第一部电影是？
2018/01/14 19:35:43 小时代
2018/01/14 19:35:43 工厂大门[标答]
2018/01/14 19:35:43 逐梦演艺圈
2018/01/14 19:35:43 朗德海花园场景

应为朗德海花园场景

2018/01/14 19:35:22 五四运动爆发与哪年？
2018/01/14 19:35:22 1919年
2018/01/14 19:35:22 1920年
2018/01/14 19:35:22 1928年[标答]
2018/01/14 19:35:22 1936年

应为1919年

**Comment by wansir** [comment]
题库中确实存在错误的情况，答题结束后会修正,`lib/db.go`
```
func cache(question Question) {
	s := fmt.Sprintf("REPLACE INTO questions(quiz, school, type, options, answer) VALUES ('%s','%s','%s','%s','%s')",
		question.Quiz, question.School, question.Type, question.Options, question.Answer)
	_,e := db.Exec(s)

	if e != nil {
		 log.Println(e)
	}
}
```
