### ISSUE TITLE
没法运行main.go

### ISSUE THREAD

**Issue by menglingkun1011** [wansir/tounao#11]
C:\Go\src\tounao>go run main.go
main.go:4:2: cannot find package "github.com/elazarl/goproxy" in any of:
        C:\Go\src\tounao\vendor\github.com\elazarl\goproxy (vendor tree)
        C:\Go\src\vendor\github.com\elazarl\goproxy
        C:\Go\src\github.com\elazarl\goproxy (from $GOROOT)
        C:\Users\MirsMeng\go\src\github.com\elazarl\goproxy (from $GOPATH)
util\util.go:5:2: cannot find package "github.com/huichen/sego" in any of:
        C:\Go\src\tounao\vendor\github.com\huichen\sego (vendor tree)
        C:\Go\src\vendor\github.com\huichen\sego
        C:\Go\src\github.com\huichen\sego (from $GOROOT)
        C:\Users\MirsMeng\go\src\github.com\huichen\sego (from $GOPATH)
lib\db.go:4:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
        C:\Go\src\tounao\vendor\github.com\mattn\go-sqlite3 (vendor tree)
        C:\Go\src\vendor\github.com\mattn\go-sqlite3
        C:\Go\src\github.com\mattn\go-sqlite3 (from $GOROOT)
        C:\Users\MirsMeng\go\src\github.com\mattn\go-sqlite3 (from $GOPATH)

**Comment by wansir** [comment]
```
echo $GOPATH
git clone git@github.com:wansir/tounao.git $(echo "$GOPATH/src/tounao")
cd  $(echo "$GOPATH/src/tounao")
git submodule init
git submodule update
```

**Comment by wansir** [comment]
```
git submodule init
git submodule update
```
需要拉取git子模块到vendor目录中
