### ISSUE TITLE
无法载入字典

### ISSUE THREAD

**Issue by a007liu** [wansir/tounao#13]
C:\GOPATH\src\tounao>go run main.go
2018/01/18 05:05:11 载入sego词典 vendor/github.com/huichen/sego/data/dictionary.
txt
2018/01/18 05:05:11 无法载入字典文件 "vendor/github.com/huichen/sego/data/dictio
nary.txt"
exit status 1

**Comment by wansir** [comment]
```
git submodule init
git submodule update
```
