### ISSUE TITLE
您好，我有个提议

### ISSUE THREAD

**Issue by RenjiaLu9527** [wansir/tounao#2]
您好，我有个提议，我前几天也做了一个python+mitmdump版的，思路和你的一样，都是设置代理拦截并标记答案并把新题存进数据库；
但是有个问题，头脑王者的题库数量至少上万，且每天都有新的题目过审；所以我想是不是可以大家都共享一个数据库，人多力量大，大家一起贡献没有被记录的新题

**Comment by wansir** [comment]
确实是，共享题库可以保证更高命中率，但我觉得刷分不是目的，认真就没得玩了，看看排行榜里都是各路神仙，写这种项目练练手，娱乐一下还是可以的

我也提供一个建议，可以把服务部署到公网，供更多人一起使用（根据roomID划分），是不是就能收集更多的题目了呢？

**Comment by RenjiaLu9527** [comment]
感谢提供题库，这8000多的题库重现率比较高了
刚更新题库里面4000-7000那一段有很多条记录的‘’school‘’ ‘’type‘’值为nil，虽然不影响获取答案，
还有有些题的答案错误
