### ISSUE TITLE
有很多依赖包都没有，一开始运行出现很多错误，现在只有这个问题，求解决？

### ISSUE THREAD

**Issue by ChiehJang** [wansir/tounao#4]
C:\Go\src>go run main.go
C:\Go\src\tounao\lib\injectior.go:11:2: non-standard import "github.com/elazarl/goproxy" in standard package "tounao/lib"
C:\Go\src\tounao\util\util.go:5:2: non-standard import "github.com/huichen/sego" in standard package "tounao/util"

**Comment by wansir** [comment]
```
go get github.com/elazarl/goproxy
go get github.com/huichen/sego
```

**Comment by wansir** [comment]
```
echo $GOPATH
git clone git@github.com:golang/net.git $(echo "$GOPATH/src/golang.org/x/net")
go get github.com/mattn/go-sqlite3
go get github.com/elazarl/goproxy
go get github.com/huichen/sego
```
