### ISSUE TITLE
设置代理后，手机打开不能下载证书

### ISSUE THREAD

**Issue by wojs5** [wansir/tounao#5]
这边显示的代理地址，和我实际的ip并不一样，不知道是不这个的原因

**Comment by wansir** [comment]
是的， 以你的实际（内网）IP为准，这里显示的 IP可能不太准确，但默认绑定的是本机8989端口

**Comment by wojs5** [comment]
但代理设置了真实ip，手机打开还是不能下载证书，搜索系统目录也没发现ca.crt文件，这里要如何操作？

**Comment by wansir** [comment]
服务默认绑定的是`0.0.0.0:8989`,所以需要你的手机和PC在同一个网段中，代理IP为PC的**局域网地址**
首先，看看你clone的版本`main.go`这一段代码有没有被注释掉
```
		if ctx.Req.URL.Hostname() == `github.com` {
			resp.StatusCode = 200
			resp.Header.Add("Content-Disposition", "attachment; filename=ca.crt")
			resp.Header.Add("Content-Type", "application/octet-stream")
			resp.Body = ioutil.NopCloser(bytes.NewReader(goproxy.CA_CERT))
		}
```
你也可以在`main.go` 中`requestHandle`这个`func`中加入 一段日志打印来判断你的代理是否生效
```
log.Println(ctx.Req.URL)
```

**Comment by wojs5** [comment]
搞定了，谢谢了，不是什么问题，我自己打错了
